// KoboldCppAutomatic syntax

{
package koboldcpp

import (
	"github.com/openai/openai-go/v3/responses"
)

type EndOfTurn int
const EOT EndOfTurn = iota
}

Prompt = (role:Role / EndOfTurn / message:.)*

Role = SystemRole / UserRole / AssistantRole
SystemRole = (
	"{{[SYSTEM]}}"
	/ NonCaptureNewLine "<start_of_turn>system\n"
) { return responses.EasyInputMessageRoleSystem, nil }
UserRole = (
	"{{[INPUT]}}"
	/ NonCaptureNewLine "### Instruction:\n"
	/ NonCaptureNewLine "<start_of_turn>user\n"
) { return responses.EasyInputMessageRoleUser, nil }
AssistantRole = (
	"{{[OUTPUT]}}"
	/ NonCaptureNewLine "### Response:\n"
	/ NonCaptureNewLine "<start_of_turn>model\n"
) { return responses.EasyInputMessageRoleAssistant, nil }

EndOfTurn = (
	NonCaptureNewLine ("{{[SYSTEM_END]}}" / "{{[INPUT_END]}}" / "{{[OUTPUT_END]}}" / "<end_of_turn>") NonCaptureNewLine
) { return EOT, nil }

NonCaptureNewLine = "\n"? { return nil, nil }