// KoboldCppAutomatic syntax

{
package koboldcpp

import (
	"github.com/openai/openai-go/v3/responses"
)
}

Prompt = (role:Role child:(
	nested:Prompt
	/ message:.
)*)

Role = SystemRole / UserRole / AssistantRole
SystemRole = "{{[SYSTEM]}}" { return responses.EasyInputMessageRoleSystem, nil }
UserRole = "{{[INPUT]}}" { return responses.EasyInputMessageRoleUser, nil }
AssistantRole = "{{[OUTPUT]}}" { return responses.EasyInputMessageRoleAssistant, nil }