// Code generated by ogen, DO NOT EDIT.

package aihorde

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// DeleteFilterSingle implements delete_filter_single operation.
	//
	// Moderator Only: Delete a regex filter.
	//
	// DELETE /v2/filters/{filter_id}
	DeleteFilterSingle(ctx context.Context, params DeleteFilterSingleParams) (DeleteFilterSingleRes, error)
	// DeleteImageAsyncStatus implements delete_image_async_status operation.
	//
	// This request will include all already generated images in base64 encoded .webp files.
	//
	// DELETE /v2/generate/status/{id}
	DeleteImageAsyncStatus(ctx context.Context, params DeleteImageAsyncStatusParams) (DeleteImageAsyncStatusRes, error)
	// DeleteInterrogationStatus implements delete_interrogation_status operation.
	//
	// This request will return all already interrogated image results.
	//
	// DELETE /v2/interrogate/status/{id}
	DeleteInterrogationStatus(ctx context.Context, params DeleteInterrogationStatusParams) (DeleteInterrogationStatusRes, error)
	// DeleteOperationsBlockWorkerIP implements delete_operations_block_worker_ip operation.
	//
	// Only usable by horde moderators.
	//
	// DELETE /v2/operations/block_worker_ipaddr/{worker_id}
	DeleteOperationsBlockWorkerIP(ctx context.Context, params DeleteOperationsBlockWorkerIPParams) (DeleteOperationsBlockWorkerIPRes, error)
	// DeleteOperationsIP implements delete_operations_ip operation.
	//
	// Only usable by horde moderators.
	//
	// DELETE /v2/operations/ipaddr
	DeleteOperationsIP(ctx context.Context, req *DeleteTimeoutIPInput, params DeleteOperationsIPParams) (DeleteOperationsIPRes, error)
	// DeleteSharedKeySingle implements delete_shared_key_single operation.
	//
	// Delete an existing SharedKey for this user.
	//
	// DELETE /v2/sharedkeys/{sharedkey_id}
	DeleteSharedKeySingle(ctx context.Context, params DeleteSharedKeySingleParams) (DeleteSharedKeySingleRes, error)
	// DeleteSingleCollection implements delete_single_collection operation.
	//
	// Deletes a style collection.
	//
	// DELETE /v2/collections/{collection_id}
	DeleteSingleCollection(ctx context.Context, params DeleteSingleCollectionParams) (DeleteSingleCollectionRes, error)
	// DeleteSingleImageStyle implements delete_single_image_style operation.
	//
	// Deletes an image style.
	//
	// DELETE /v2/styles/image/{style_id}
	DeleteSingleImageStyle(ctx context.Context, params DeleteSingleImageStyleParams) (DeleteSingleImageStyleRes, error)
	// DeleteSingleImageStyleExample implements delete_single_image_style_example operation.
	//
	// Deletes an image style example.
	//
	// DELETE /v2/styles/image/{style_id}/example/{example_id}
	DeleteSingleImageStyleExample(ctx context.Context, params DeleteSingleImageStyleExampleParams) (DeleteSingleImageStyleExampleRes, error)
	// DeleteSingleTextStyle implements delete_single_text_style operation.
	//
	// Deletes a text style.
	//
	// DELETE /v2/styles/text/{style_id}
	DeleteSingleTextStyle(ctx context.Context, params DeleteSingleTextStyleParams) (DeleteSingleTextStyleRes, error)
	// DeleteSingleWorkerMessage implements delete_single_worker_message operation.
	//
	// Delete a Worker Message.
	//
	// DELETE /v2/workers/messages/{message_id}
	DeleteSingleWorkerMessage(ctx context.Context, params DeleteSingleWorkerMessageParams) (*SimpleResponse, error)
	// DeleteTeamSingle implements delete_team_single operation.
	//
	// Only the team's creator or a horde moderator can use this endpoint. This action is unrecoverable!.
	//
	// DELETE /v2/teams/{team_id}
	DeleteTeamSingle(ctx context.Context, params DeleteTeamSingleParams) (DeleteTeamSingleRes, error)
	// DeleteTextAsyncStatus implements delete_text_async_status operation.
	//
	// This request will include all already generated texts.
	//
	// DELETE /v2/generate/text/status/{id}
	DeleteTextAsyncStatus(ctx context.Context, params DeleteTextAsyncStatusParams) (DeleteTextAsyncStatusRes, error)
	// DeleteUserSingle implements delete_user_single operation.
	//
	// Only the user or a horde moderator can use this endpoint. A deleted user will initially be hidden
	// and cannot be used anymore After a month of being set as deleted, the same request will wipe the
	// user permanently this action is then irreversible!.
	//
	// DELETE /v2/users/{user_id}
	DeleteUserSingle(ctx context.Context, params DeleteUserSingleParams) (DeleteUserSingleRes, error)
	// DeleteWorkerSingle implements delete_worker_single operation.
	//
	// This will delete the worker and their statistics. Will not affect the kudos generated by that worker
	// for their owner. Only the worker's owner and an admin can use this endpoint. This action is
	// unrecoverable!.
	//
	// DELETE /v2/workers/{worker_id}
	DeleteWorkerSingle(ctx context.Context, params DeleteWorkerSingleParams) (DeleteWorkerSingleRes, error)
	// GetCollection implements get_collection operation.
	//
	// Can filter by type.
	//
	// GET /v2/collections
	GetCollection(ctx context.Context, params GetCollectionParams) ([]ResponseModelCollection, error)
	// GetDocsPrivacy implements get_docs_privacy operation.
	//
	// Privacy Policy.
	//
	// GET /v2/documents/privacy
	GetDocsPrivacy(ctx context.Context, params GetDocsPrivacyParams) (GetDocsPrivacyRes, error)
	// GetDocsSponsors implements get_docs_sponsors operation.
	//
	// Sponsors.
	//
	// GET /v2/documents/sponsors
	GetDocsSponsors(ctx context.Context, params GetDocsSponsorsParams) (GetDocsSponsorsRes, error)
	// GetDocsTerms implements get_docs_terms operation.
	//
	// Terms and Conditions.
	//
	// GET /v2/documents/terms
	GetDocsTerms(ctx context.Context, params GetDocsTermsParams) (GetDocsTermsRes, error)
	// GetFilterRegex implements get_filter_regex operation.
	//
	// Moderator Only: A List all filters, or filtered by the query.
	//
	// GET /v2/filters/regex
	GetFilterRegex(ctx context.Context, params GetFilterRegexParams) (GetFilterRegexRes, error)
	// GetFilterSingle implements get_filter_single operation.
	//
	// Moderator Only: Display a single filter.
	//
	// GET /v2/filters/{filter_id}
	GetFilterSingle(ctx context.Context, params GetFilterSingleParams) (GetFilterSingleRes, error)
	// GetFilters implements get_filters operation.
	//
	// Moderator Only: A List all filters, or filtered by the query.
	//
	// GET /v2/filters
	GetFilters(ctx context.Context, params GetFiltersParams) (GetFiltersRes, error)
	// GetFindUser implements get_find_user operation.
	//
	// This can be used to verify a user exists.
	//
	// GET /v2/find_user
	GetFindUser(ctx context.Context, params GetFindUserParams) (GetFindUserRes, error)
	// GetHeartbeat implements get_heartbeat operation.
	//
	// Includes some other metrics to gauge the health of this node.
	//
	// GET /v2/status/heartbeat
	GetHeartbeat(ctx context.Context, params GetHeartbeatParams) error
	// GetHordeLoad implements get_horde_load operation.
	//
	// Details about the current performance of this Horde.
	//
	// GET /v2/status/performance
	GetHordeLoad(ctx context.Context, params GetHordeLoadParams) (*HordePerformance, error)
	// GetHordeModes implements get_horde_modes operation.
	//
	// Use this endpoint to quicky determine if this horde is in maintenance, invite_only or raid mode.
	//
	// GET /v2/status/modes
	GetHordeModes(ctx context.Context, params GetHordeModesParams) (*HordeModes, error)
	// GetHordeNews implements get_horde_news operation.
	//
	// Read the latest happenings on the horde.
	//
	// GET /v2/status/news
	GetHordeNews(ctx context.Context, params GetHordeNewsParams) ([]Newspiece, error)
	// GetImageAsyncCheck implements get_image_async_check operation.
	//
	// Use this request to check the status of a currently running asynchronous request without consuming
	// bandwidth.
	//
	// GET /v2/generate/check/{id}
	GetImageAsyncCheck(ctx context.Context, params GetImageAsyncCheckParams) (GetImageAsyncCheckRes, error)
	// GetImageAsyncStatus implements get_image_async_status operation.
	//
	// This request will include all already generated images in download URL or base64 encoded .webp
	// files. As such, you are requested to not retrieve this endpoint often. Instead use the /check/
	// endpoint first This endpoint is limited to 10 request per minute.
	//
	// GET /v2/generate/status/{id}
	GetImageAsyncStatus(ctx context.Context, params GetImageAsyncStatusParams) (GetImageAsyncStatusRes, error)
	// GetImageHordeStatsModels implements get_image_horde_stats_models operation.
	//
	// Details how many images were generated per model for the past day, month and total.
	//
	// GET /v2/stats/img/models
	GetImageHordeStatsModels(ctx context.Context, params GetImageHordeStatsModelsParams) (GetImageHordeStatsModelsRes, error)
	// GetImageHordeStatsTotals implements get_image_horde_stats_totals operation.
	//
	// Also shows the amount of pixelsteps for the same timeframe.
	//
	// GET /v2/stats/img/totals
	GetImageHordeStatsTotals(ctx context.Context, params GetImageHordeStatsTotalsParams) (*StatsImgTotals, error)
	// GetImageStyle implements get_image_style operation.
	//
	// Can be filtered based on model or tags.
	//
	// GET /v2/styles/image
	GetImageStyle(ctx context.Context, params GetImageStyleParams) ([]StyleStable, error)
	// GetInterrogationStatus implements get_interrogation_status operation.
	//
	// This request will include all already generated images. As such, you are requested to not retrieve
	// this endpoint often. Instead use the /check/ endpoint first.
	//
	// GET /v2/interrogate/status/{id}
	GetInterrogationStatus(ctx context.Context, params GetInterrogationStatusParams) (GetInterrogationStatusRes, error)
	// GetModelSingle implements get_model_single operation.
	//
	// Returns all the statistics of a specific model in this horde.
	//
	// GET /v2/status/models/{model_name}
	GetModelSingle(ctx context.Context, params GetModelSingleParams) ([]ActiveModel, error)
	// GetModels implements get_models operation.
	//
	// Returns a list of models active currently in this horde.
	//
	// GET /v2/status/models
	GetModels(ctx context.Context, params GetModelsParams) (GetModelsRes, error)
	// GetOperationsIP implements get_operations_ip operation.
	//
	// Return all existing IP Block timeouts.
	//
	// GET /v2/operations/ipaddr
	GetOperationsIP(ctx context.Context, params GetOperationsIPParams) (GetOperationsIPRes, error)
	// GetOperationsIPSingle implements get_operations_ip_single operation.
	//
	// Check if an IP or CIDR is in timeout.
	//
	// GET /v2/operations/ipaddr/{ipaddr}
	GetOperationsIPSingle(ctx context.Context, params GetOperationsIPSingleParams) (GetOperationsIPSingleRes, error)
	// GetSharedKeySingle implements get_shared_key_single operation.
	//
	// Get details about an existing Shared Key.
	//
	// GET /v2/sharedkeys/{sharedkey_id}
	GetSharedKeySingle(ctx context.Context, params GetSharedKeySingleParams) (GetSharedKeySingleRes, error)
	// GetSingleCollection implements get_single_collection operation.
	//
	// Displays information about a single style collection.
	//
	// GET /v2/collections/{collection_id}
	GetSingleCollection(ctx context.Context, params GetSingleCollectionParams) (*ResponseModelCollection, error)
	// GetSingleCollectionByName implements get_single_collection_by_name operation.
	//
	// Seeks an style collection by name and displays its information.
	//
	// GET /v2/collection_by_name/{collection_name}
	GetSingleCollectionByName(ctx context.Context, params GetSingleCollectionByNameParams) (*ResponseModelCollection, error)
	// GetSingleImageStyle implements get_single_image_style operation.
	//
	// Displays information about an image style.
	//
	// GET /v2/styles/image/{style_id}
	GetSingleImageStyle(ctx context.Context, params GetSingleImageStyleParams) (*StyleStable, error)
	// GetSingleImageStyleByName implements get_single_image_style_by_name operation.
	//
	// Seeks an image style by name and displays its information.
	//
	// GET /v2/styles/image_by_name/{style_name}
	GetSingleImageStyleByName(ctx context.Context, params GetSingleImageStyleByNameParams) (*StyleStable, error)
	// GetSingleTextStyle implements get_single_text_style operation.
	//
	// Displays information about a single text style.
	//
	// GET /v2/styles/text/{style_id}
	GetSingleTextStyle(ctx context.Context, params GetSingleTextStyleParams) (*StyleKobold, error)
	// GetSingleTextStyleByName implements get_single_text_style_by_name operation.
	//
	// Seeks a text style by name and displays its information.
	//
	// GET /v2/styles/text_by_name/{style_name}
	GetSingleTextStyleByName(ctx context.Context, params GetSingleTextStyleByNameParams) (*StyleKobold, error)
	// GetSingleWorkerMessage implements get_single_worker_message operation.
	//
	// Display a Worker Message.
	//
	// GET /v2/workers/messages/{message_id}
	GetSingleWorkerMessage(ctx context.Context, params GetSingleWorkerMessageParams) (*ResponseModelMessage, error)
	// GetTeamSingle implements get_team_single operation.
	//
	// Details of a worker Team.
	//
	// GET /v2/teams/{team_id}
	GetTeamSingle(ctx context.Context, params GetTeamSingleParams) (GetTeamSingleRes, error)
	// GetTeams implements get_teams operation.
	//
	// A List with the details of all teams.
	//
	// GET /v2/teams
	GetTeams(ctx context.Context, params GetTeamsParams) ([]TeamDetails, error)
	// GetTextAsyncStatus implements get_text_async_status operation.
	//
	// This request will include all already generated texts.
	//
	// GET /v2/generate/text/status/{id}
	GetTextAsyncStatus(ctx context.Context, params GetTextAsyncStatusParams) (GetTextAsyncStatusRes, error)
	// GetTextHordeStatsModels implements get_text_horde_stats_models operation.
	//
	// Details how many texts were generated per model for the past day, month and total.
	//
	// GET /v2/stats/text/models
	GetTextHordeStatsModels(ctx context.Context, params GetTextHordeStatsModelsParams) (*TxtModelStats, error)
	// GetTextHordeStatsTotals implements get_text_horde_stats_totals operation.
	//
	// Also shows the amount of pixelsteps for the same timeframe.
	//
	// GET /v2/stats/text/totals
	GetTextHordeStatsTotals(ctx context.Context, params GetTextHordeStatsTotalsParams) (*StatsTxtTotals, error)
	// GetTextStyle implements get_text_style operation.
	//
	// Can be filtered based on model or tags.
	//
	// GET /v2/styles/text
	GetTextStyle(ctx context.Context, params GetTextStyleParams) ([]StyleKobold, error)
	// GetUserSingle implements get_user_single operation.
	//
	// Details and statistics about a specific user.
	//
	// GET /v2/users/{user_id}
	GetUserSingle(ctx context.Context, params GetUserSingleParams) (GetUserSingleRes, error)
	// GetUsers implements get_users operation.
	//
	// A List with the details and statistic of all registered users.
	//
	// GET /v2/users
	GetUsers(ctx context.Context, params GetUsersParams) (*UserDetails, error)
	// GetWorkerMessages implements get_worker_messages operation.
	//
	// List Worker Messages.
	//
	// GET /v2/workers/messages
	GetWorkerMessages(ctx context.Context, params GetWorkerMessagesParams) (GetWorkerMessagesRes, error)
	// GetWorkerSingle implements get_worker_single operation.
	//
	// Can retrieve the details of a worker even if inactive (A worker is considered inactive if it has not
	// checked in for 5 minutes).
	//
	// GET /v2/workers/{worker_id}
	GetWorkerSingle(ctx context.Context, params GetWorkerSingleParams) (GetWorkerSingleRes, error)
	// GetWorkerSingleName implements get_worker_single_name operation.
	//
	// Can retrieve the details of a worker even if inactive (A worker is considered inactive if it has not
	// checked in for 5 minutes).
	//
	// GET /v2/workers/name/{worker_name}
	GetWorkerSingleName(ctx context.Context, params GetWorkerSingleNameParams) (GetWorkerSingleNameRes, error)
	// GetWorkers implements get_workers operation.
	//
	// A List with the details of all registered and active workers.
	//
	// GET /v2/workers
	GetWorkers(ctx context.Context, params GetWorkersParams) ([]WorkerDetails, error)
	// PatchFilterSingle implements patch_filter_single operation.
	//
	// Moderator Only: Modify an existing regex filter.
	//
	// PATCH /v2/filters/{filter_id}
	PatchFilterSingle(ctx context.Context, req *PatchExistingFilter, params PatchFilterSingleParams) (PatchFilterSingleRes, error)
	// PatchSharedKeySingle implements patch_shared_key_single operation.
	//
	// Modify an existing Shared Key.
	//
	// PATCH /v2/sharedkeys/{sharedkey_id}
	PatchSharedKeySingle(ctx context.Context, req *SharedKeyInput, params PatchSharedKeySingleParams) (PatchSharedKeySingleRes, error)
	// PatchSingleCollection implements patch_single_collection operation.
	//
	// Modifies an existing style collection.
	//
	// PATCH /v2/collections/{collection_id}
	PatchSingleCollection(ctx context.Context, req *InputModelCollection, params PatchSingleCollectionParams) (PatchSingleCollectionRes, error)
	// PatchSingleImageStyle implements patch_single_image_style operation.
	//
	// Modifies an image style.
	//
	// PATCH /v2/styles/image/{style_id}
	PatchSingleImageStyle(ctx context.Context, req *ModelStylePatchStable, params PatchSingleImageStyleParams) (PatchSingleImageStyleRes, error)
	// PatchSingleImageStyleExample implements patch_single_image_style_example operation.
	//
	// Modified an existing image style example.
	//
	// PATCH /v2/styles/image/{style_id}/example/{example_id}
	PatchSingleImageStyleExample(ctx context.Context, req *InputStyleExamplePost, params PatchSingleImageStyleExampleParams) (PatchSingleImageStyleExampleRes, error)
	// PatchSingleTextStyle implements patch_single_text_style operation.
	//
	// Modifies a text style.
	//
	// PATCH /v2/styles/text/{style_id}
	PatchSingleTextStyle(ctx context.Context, req *ModelStylePatchKobold, params PatchSingleTextStyleParams) (PatchSingleTextStyleRes, error)
	// PatchTeamSingle implements patch_team_single operation.
	//
	// Update a Team's information.
	//
	// PATCH /v2/teams/{team_id}
	PatchTeamSingle(ctx context.Context, req *ModifyTeamInput, params PatchTeamSingleParams) (PatchTeamSingleRes, error)
	// PostAesthetics implements post_aesthetics operation.
	//
	// AI The request has to have been sent as shared: true. You can select the best image in the set,
	// and/or provide a rating for each or some images in the set. If you select best-of image, you will
	// gain 4 kudos. Each rating is 5 kudos. Best-of will be ignored when ratings conflict with it. You can
	// never gain more kudos than you spent for this generation. Your reward at max will be your kudos
	// consumption - 1.
	//
	// POST /v2/generate/rate/{id}
	PostAesthetics(ctx context.Context, req *AestheticsPayload, params PostAestheticsParams) (PostAestheticsRes, error)
	// PostAwardKudos implements post_award_kudos operation.
	//
	// This API can only be used through privileged access.
	//
	// POST /v2/kudos/award
	PostAwardKudos(ctx context.Context, req *PostAwardKudosReq, params PostAwardKudosParams) (PostAwardKudosRes, error)
	// PostCollection implements post_collection operation.
	//
	// Creates a new style collection.
	//
	// POST /v2/collections
	PostCollection(ctx context.Context, req *InputModelCollection, params PostCollectionParams) (PostCollectionRes, error)
	// PostFilters implements post_filters operation.
	//
	// Moderator Only: Check The suspicion of the provided prompt.
	//
	// POST /v2/filters
	PostFilters(ctx context.Context, req *PostFiltersReq, params PostFiltersParams) (PostFiltersRes, error)
	// PostImageAsyncGenerate implements post_image_async_generate operation.
	//
	// This endpoint will immediately return with the UUID of the request for generation. This endpoint
	// will always be accepted, even if there are no workers available currently to fulfill this request.
	// Perhaps some will appear in the next 10 minutes. Asynchronous requests live for 10 minutes before
	// being considered stale and being deleted.
	//
	// POST /v2/generate/async
	PostImageAsyncGenerate(ctx context.Context, req *GenerationInputStable, params PostImageAsyncGenerateParams) (PostImageAsyncGenerateRes, error)
	// PostImageJobPop implements post_image_job_pop operation.
	//
	// This endpoint is used by registered workers only.
	//
	// POST /v2/generate/pop
	PostImageJobPop(ctx context.Context, req *PopInputStable, params PostImageJobPopParams) (PostImageJobPopRes, error)
	// PostImageJobSubmit implements post_image_job_submit operation.
	//
	// This endpoint is used by registered workers only.
	//
	// POST /v2/generate/submit
	PostImageJobSubmit(ctx context.Context, req *SubmitInputStable, params PostImageJobSubmitParams) (PostImageJobSubmitRes, error)
	// PostImageStyle implements post_image_style operation.
	//
	// Creates a new image style.
	//
	// POST /v2/styles/image
	PostImageStyle(ctx context.Context, req *ModelStyleInputStable, params PostImageStyleParams) (PostImageStyleRes, error)
	// PostImageStyleExample implements post_image_style_example operation.
	//
	// Creates an image style example.
	//
	// POST /v2/styles/image/{style_id}/example
	PostImageStyleExample(ctx context.Context, req *InputStyleExamplePost, params PostImageStyleExampleParams) (PostImageStyleExampleRes, error)
	// PostInterrogate implements post_interrogate operation.
	//
	// This endpoint will immediately return with the UUID of the request for interrogation. This endpoint
	// will always be accepted, even if there are no workers available currently to fulfill this request.
	// Perhaps some will appear in the next 20 minutes. Asynchronous requests live for 20 minutes before
	// being considered stale and being deleted.
	//
	// POST /v2/interrogate/async
	PostInterrogate(ctx context.Context, req *ModelInterrogationInputStable, params PostInterrogateParams) (PostInterrogateRes, error)
	// PostInterrogatePop implements post_interrogate_pop operation.
	//
	// This endpoint is used by registered workers only.
	//
	// POST /v2/interrogate/pop
	PostInterrogatePop(ctx context.Context, req *InterrogationPopInput, params PostInterrogatePopParams) (PostInterrogatePopRes, error)
	// PostInterrogateSubmit implements post_interrogate_submit operation.
	//
	// This endpoint is used by registered workers only.
	//
	// POST /v2/interrogate/submit
	PostInterrogateSubmit(ctx context.Context, req *PostInterrogateSubmitReq, params PostInterrogateSubmitParams) (PostInterrogateSubmitRes, error)
	// PostOperationsIP implements post_operations_ip operation.
	//
	// Only usable by horde moderators.
	//
	// POST /v2/operations/ipaddr
	PostOperationsIP(ctx context.Context, req *AddTimeoutIPInput, params PostOperationsIPParams) (PostOperationsIPRes, error)
	// PostTeams implements post_teams operation.
	//
	// Only trusted users can create new teams.
	//
	// POST /v2/teams
	PostTeams(ctx context.Context, req *CreateTeamInput, params PostTeamsParams) (PostTeamsRes, error)
	// PostTextAsyncGenerate implements post_text_async_generate operation.
	//
	// This endpoint will immediately return with the UUID of the request for generation. This endpoint
	// will always be accepted, even if there are no workers available currently to fulfill this request.
	// Perhaps some will appear in the next 20 minutes. Asynchronous requests live for 20 minutes before
	// being considered stale and being deleted.
	//
	// POST /v2/generate/text/async
	PostTextAsyncGenerate(ctx context.Context, req *GenerationInputKobold, params PostTextAsyncGenerateParams) (PostTextAsyncGenerateRes, error)
	// PostTextJobPop implements post_text_job_pop operation.
	//
	// This endpoint is used by registered workers only.
	//
	// POST /v2/generate/text/pop
	PostTextJobPop(ctx context.Context, req *PopInputKobold, params PostTextJobPopParams) (PostTextJobPopRes, error)
	// PostTextJobSubmit implements post_text_job_submit operation.
	//
	// This endpoint is used by registered workers only.
	//
	// POST /v2/generate/text/submit
	PostTextJobSubmit(ctx context.Context, req *SubmitInputKobold, params PostTextJobSubmitParams) (PostTextJobSubmitRes, error)
	// PostTextStyle implements post_text_style operation.
	//
	// Creates a new text style.
	//
	// POST /v2/styles/text
	PostTextStyle(ctx context.Context, req *ModelStyleInputKobold, params PostTextStyleParams) (PostTextStyleRes, error)
	// PostTransferKudos implements post_transfer_kudos operation.
	//
	// Transfer Kudos to another registed user.
	//
	// POST /v2/kudos/transfer
	PostTransferKudos(ctx context.Context, req *PostTransferKudosReq, params PostTransferKudosParams) (PostTransferKudosRes, error)
	// PostWorkerMessages implements post_worker_messages operation.
	//
	// Create New Worker Message.
	//
	// POST /v2/workers/messages
	PostWorkerMessages(ctx context.Context, req *ResponseModelMessage, params PostWorkerMessagesParams) (PostWorkerMessagesRes, error)
	// PutFilters implements put_filters operation.
	//
	// Moderator Only: Add a new regex filter.
	//
	// PUT /v2/filters
	PutFilters(ctx context.Context, req *PutNewFilter, params PutFiltersParams) (PutFiltersRes, error)
	// PutHordeModes implements put_horde_modes operation.
	//
	// Endpoint for admins to (un)set the horde into maintenance, invite_only or raid modes.
	//
	// PUT /v2/status/modes
	PutHordeModes(ctx context.Context, req *PutHordeModesReq, params PutHordeModesParams) (PutHordeModesRes, error)
	// PutOperationsBlockWorkerIP implements put_operations_block_worker_ip operation.
	//
	// Only usable by horde moderators.
	//
	// PUT /v2/operations/block_worker_ipaddr/{worker_id}
	PutOperationsBlockWorkerIP(ctx context.Context, req *AddWorkerTimeout, params PutOperationsBlockWorkerIPParams) (PutOperationsBlockWorkerIPRes, error)
	// PutSharedKey implements put_shared_key operation.
	//
	// Create a new SharedKey for this user.
	//
	// PUT /v2/sharedkeys
	PutSharedKey(ctx context.Context, req *SharedKeyInput, params PutSharedKeyParams) (PutSharedKeyRes, error)
	// PutUserSingle implements put_user_single operation.
	//
	// Endpoint for horde admins to perform operations on users.
	//
	// PUT /v2/users/{user_id}
	PutUserSingle(ctx context.Context, req *ModifyUserInput, params PutUserSingleParams) (PutUserSingleRes, error)
	// PutWorkerSingle implements put_worker_single operation.
	//
	// PUT /v2/workers/{worker_id}
	PutWorkerSingle(ctx context.Context, req *ModifyWorkerInput, params PutWorkerSingleParams) (PutWorkerSingleRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
