// Code generated by ogen, DO NOT EDIT.

package aihorde

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// DeleteFilterSingle implements delete_filter_single operation.
//
// Moderator Only: Delete a regex filter.
//
// DELETE /v2/filters/{filter_id}
func (UnimplementedHandler) DeleteFilterSingle(ctx context.Context, params DeleteFilterSingleParams) (r DeleteFilterSingleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteImageAsyncStatus implements delete_image_async_status operation.
//
// This request will include all already generated images in base64 encoded .webp files.
//
// DELETE /v2/generate/status/{id}
func (UnimplementedHandler) DeleteImageAsyncStatus(ctx context.Context, params DeleteImageAsyncStatusParams) (r DeleteImageAsyncStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteInterrogationStatus implements delete_interrogation_status operation.
//
// This request will return all already interrogated image results.
//
// DELETE /v2/interrogate/status/{id}
func (UnimplementedHandler) DeleteInterrogationStatus(ctx context.Context, params DeleteInterrogationStatusParams) (r DeleteInterrogationStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteOperationsBlockWorkerIP implements delete_operations_block_worker_ip operation.
//
// Only usable by horde moderators.
//
// DELETE /v2/operations/block_worker_ipaddr/{worker_id}
func (UnimplementedHandler) DeleteOperationsBlockWorkerIP(ctx context.Context, params DeleteOperationsBlockWorkerIPParams) (r DeleteOperationsBlockWorkerIPRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteOperationsIP implements delete_operations_ip operation.
//
// Only usable by horde moderators.
//
// DELETE /v2/operations/ipaddr
func (UnimplementedHandler) DeleteOperationsIP(ctx context.Context, req *DeleteTimeoutIPInput, params DeleteOperationsIPParams) (r DeleteOperationsIPRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSharedKeySingle implements delete_shared_key_single operation.
//
// Delete an existing SharedKey for this user.
//
// DELETE /v2/sharedkeys/{sharedkey_id}
func (UnimplementedHandler) DeleteSharedKeySingle(ctx context.Context, params DeleteSharedKeySingleParams) (r DeleteSharedKeySingleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSingleCollection implements delete_single_collection operation.
//
// Deletes a style collection.
//
// DELETE /v2/collections/{collection_id}
func (UnimplementedHandler) DeleteSingleCollection(ctx context.Context, params DeleteSingleCollectionParams) (r DeleteSingleCollectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSingleImageStyle implements delete_single_image_style operation.
//
// Deletes an image style.
//
// DELETE /v2/styles/image/{style_id}
func (UnimplementedHandler) DeleteSingleImageStyle(ctx context.Context, params DeleteSingleImageStyleParams) (r DeleteSingleImageStyleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSingleImageStyleExample implements delete_single_image_style_example operation.
//
// Deletes an image style example.
//
// DELETE /v2/styles/image/{style_id}/example/{example_id}
func (UnimplementedHandler) DeleteSingleImageStyleExample(ctx context.Context, params DeleteSingleImageStyleExampleParams) (r DeleteSingleImageStyleExampleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSingleTextStyle implements delete_single_text_style operation.
//
// Deletes a text style.
//
// DELETE /v2/styles/text/{style_id}
func (UnimplementedHandler) DeleteSingleTextStyle(ctx context.Context, params DeleteSingleTextStyleParams) (r DeleteSingleTextStyleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSingleWorkerMessage implements delete_single_worker_message operation.
//
// Delete a Worker Message.
//
// DELETE /v2/workers/messages/{message_id}
func (UnimplementedHandler) DeleteSingleWorkerMessage(ctx context.Context, params DeleteSingleWorkerMessageParams) (r *SimpleResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTeamSingle implements delete_team_single operation.
//
// Only the team's creator or a horde moderator can use this endpoint.
// This action is unrecoverable!.
//
// DELETE /v2/teams/{team_id}
func (UnimplementedHandler) DeleteTeamSingle(ctx context.Context, params DeleteTeamSingleParams) (r DeleteTeamSingleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTextAsyncStatus implements delete_text_async_status operation.
//
// This request will include all already generated texts.
//
// DELETE /v2/generate/text/status/{id}
func (UnimplementedHandler) DeleteTextAsyncStatus(ctx context.Context, params DeleteTextAsyncStatusParams) (r DeleteTextAsyncStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteUserSingle implements delete_user_single operation.
//
// Only the user or a horde moderator can use this endpoint.
// A deleted user will initially be hidden and cannot be used anymore
// After a month of being set as deleted, the same request will wipe the user permanently this action
// is then irreversible!.
//
// DELETE /v2/users/{user_id}
func (UnimplementedHandler) DeleteUserSingle(ctx context.Context, params DeleteUserSingleParams) (r DeleteUserSingleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteWorkerSingle implements delete_worker_single operation.
//
// This will delete the worker and their statistics. Will not affect the kudos generated by that
// worker for their owner.
// Only the worker's owner and an admin can use this endpoint.
// This action is unrecoverable!.
//
// DELETE /v2/workers/{worker_id}
func (UnimplementedHandler) DeleteWorkerSingle(ctx context.Context, params DeleteWorkerSingleParams) (r DeleteWorkerSingleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCollection implements get_collection operation.
//
// Can filter by type.
//
// GET /v2/collections
func (UnimplementedHandler) GetCollection(ctx context.Context, params GetCollectionParams) (r []ResponseModelCollection, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDocsPrivacy implements get_docs_privacy operation.
//
// Privacy Policy.
//
// GET /v2/documents/privacy
func (UnimplementedHandler) GetDocsPrivacy(ctx context.Context, params GetDocsPrivacyParams) (r GetDocsPrivacyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDocsSponsors implements get_docs_sponsors operation.
//
// Sponsors.
//
// GET /v2/documents/sponsors
func (UnimplementedHandler) GetDocsSponsors(ctx context.Context, params GetDocsSponsorsParams) (r GetDocsSponsorsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDocsTerms implements get_docs_terms operation.
//
// Terms and Conditions.
//
// GET /v2/documents/terms
func (UnimplementedHandler) GetDocsTerms(ctx context.Context, params GetDocsTermsParams) (r GetDocsTermsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFilterRegex implements get_filter_regex operation.
//
// Moderator Only: A List all filters, or filtered by the query.
//
// GET /v2/filters/regex
func (UnimplementedHandler) GetFilterRegex(ctx context.Context, params GetFilterRegexParams) (r GetFilterRegexRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFilterSingle implements get_filter_single operation.
//
// Moderator Only: Display a single filter.
//
// GET /v2/filters/{filter_id}
func (UnimplementedHandler) GetFilterSingle(ctx context.Context, params GetFilterSingleParams) (r GetFilterSingleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFilters implements get_filters operation.
//
// Moderator Only: A List all filters, or filtered by the query.
//
// GET /v2/filters
func (UnimplementedHandler) GetFilters(ctx context.Context, params GetFiltersParams) (r GetFiltersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFindUser implements get_find_user operation.
//
// This can be used to verify a user exists.
//
// GET /v2/find_user
func (UnimplementedHandler) GetFindUser(ctx context.Context, params GetFindUserParams) (r GetFindUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHeartbeat implements get_heartbeat operation.
//
// Includes some other metrics to gauge the health of this node.
//
// GET /v2/status/heartbeat
func (UnimplementedHandler) GetHeartbeat(ctx context.Context, params GetHeartbeatParams) error {
	return ht.ErrNotImplemented
}

// GetHordeLoad implements get_horde_load operation.
//
// Details about the current performance of this Horde.
//
// GET /v2/status/performance
func (UnimplementedHandler) GetHordeLoad(ctx context.Context, params GetHordeLoadParams) (r *HordePerformance, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHordeModes implements get_horde_modes operation.
//
// Use this endpoint to quicky determine if this horde is in maintenance, invite_only or raid mode.
//
// GET /v2/status/modes
func (UnimplementedHandler) GetHordeModes(ctx context.Context, params GetHordeModesParams) (r *HordeModes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHordeNews implements get_horde_news operation.
//
// Read the latest happenings on the horde.
//
// GET /v2/status/news
func (UnimplementedHandler) GetHordeNews(ctx context.Context, params GetHordeNewsParams) (r []Newspiece, _ error) {
	return r, ht.ErrNotImplemented
}

// GetImageAsyncCheck implements get_image_async_check operation.
//
// Use this request to check the status of a currently running asynchronous request without consuming
// bandwidth.
//
// GET /v2/generate/check/{id}
func (UnimplementedHandler) GetImageAsyncCheck(ctx context.Context, params GetImageAsyncCheckParams) (r GetImageAsyncCheckRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetImageAsyncStatus implements get_image_async_status operation.
//
// This request will include all already generated images in download URL or base64 encoded .webp
// files.
// As such, you are requested to not retrieve this endpoint often. Instead use the /check/ endpoint
// first
// This endpoint is limited to 10 request per minute.
//
// GET /v2/generate/status/{id}
func (UnimplementedHandler) GetImageAsyncStatus(ctx context.Context, params GetImageAsyncStatusParams) (r GetImageAsyncStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetImageHordeStatsModels implements get_image_horde_stats_models operation.
//
// Details how many images were generated per model for the past day, month and total.
//
// GET /v2/stats/img/models
func (UnimplementedHandler) GetImageHordeStatsModels(ctx context.Context, params GetImageHordeStatsModelsParams) (r GetImageHordeStatsModelsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetImageHordeStatsTotals implements get_image_horde_stats_totals operation.
//
// Also shows the amount of pixelsteps for the same timeframe.
//
// GET /v2/stats/img/totals
func (UnimplementedHandler) GetImageHordeStatsTotals(ctx context.Context, params GetImageHordeStatsTotalsParams) (r *StatsImgTotals, _ error) {
	return r, ht.ErrNotImplemented
}

// GetImageStyle implements get_image_style operation.
//
// Can be filtered based on model or tags.
//
// GET /v2/styles/image
func (UnimplementedHandler) GetImageStyle(ctx context.Context, params GetImageStyleParams) (r []StyleStable, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInterrogationStatus implements get_interrogation_status operation.
//
// This request will include all already generated images.
// As such, you are requested to not retrieve this endpoint often. Instead use the /check/ endpoint
// first.
//
// GET /v2/interrogate/status/{id}
func (UnimplementedHandler) GetInterrogationStatus(ctx context.Context, params GetInterrogationStatusParams) (r GetInterrogationStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetModelSingle implements get_model_single operation.
//
// Returns all the statistics of a specific model in this horde.
//
// GET /v2/status/models/{model_name}
func (UnimplementedHandler) GetModelSingle(ctx context.Context, params GetModelSingleParams) (r []ActiveModel, _ error) {
	return r, ht.ErrNotImplemented
}

// GetModels implements get_models operation.
//
// Returns a list of models active currently in this horde.
//
// GET /v2/status/models
func (UnimplementedHandler) GetModels(ctx context.Context, params GetModelsParams) (r GetModelsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOperationsIP implements get_operations_ip operation.
//
// Return all existing IP Block timeouts.
//
// GET /v2/operations/ipaddr
func (UnimplementedHandler) GetOperationsIP(ctx context.Context, params GetOperationsIPParams) (r GetOperationsIPRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOperationsIPSingle implements get_operations_ip_single operation.
//
// Check if an IP or CIDR is in timeout.
//
// GET /v2/operations/ipaddr/{ipaddr}
func (UnimplementedHandler) GetOperationsIPSingle(ctx context.Context, params GetOperationsIPSingleParams) (r GetOperationsIPSingleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSharedKeySingle implements get_shared_key_single operation.
//
// Get details about an existing Shared Key.
//
// GET /v2/sharedkeys/{sharedkey_id}
func (UnimplementedHandler) GetSharedKeySingle(ctx context.Context, params GetSharedKeySingleParams) (r GetSharedKeySingleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSingleCollection implements get_single_collection operation.
//
// Displays information about a single style collection.
//
// GET /v2/collections/{collection_id}
func (UnimplementedHandler) GetSingleCollection(ctx context.Context, params GetSingleCollectionParams) (r *ResponseModelCollection, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSingleCollectionByName implements get_single_collection_by_name operation.
//
// Seeks an style collection by name and displays its information.
//
// GET /v2/collection_by_name/{collection_name}
func (UnimplementedHandler) GetSingleCollectionByName(ctx context.Context, params GetSingleCollectionByNameParams) (r *ResponseModelCollection, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSingleImageStyle implements get_single_image_style operation.
//
// Displays information about an image style.
//
// GET /v2/styles/image/{style_id}
func (UnimplementedHandler) GetSingleImageStyle(ctx context.Context, params GetSingleImageStyleParams) (r *StyleStable, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSingleImageStyleByName implements get_single_image_style_by_name operation.
//
// Seeks an image style by name and displays its information.
//
// GET /v2/styles/image_by_name/{style_name}
func (UnimplementedHandler) GetSingleImageStyleByName(ctx context.Context, params GetSingleImageStyleByNameParams) (r *StyleStable, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSingleTextStyle implements get_single_text_style operation.
//
// Displays information about a single text style.
//
// GET /v2/styles/text/{style_id}
func (UnimplementedHandler) GetSingleTextStyle(ctx context.Context, params GetSingleTextStyleParams) (r *StyleKobold, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSingleTextStyleByName implements get_single_text_style_by_name operation.
//
// Seeks a text style by name and displays its information.
//
// GET /v2/styles/text_by_name/{style_name}
func (UnimplementedHandler) GetSingleTextStyleByName(ctx context.Context, params GetSingleTextStyleByNameParams) (r *StyleKobold, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSingleWorkerMessage implements get_single_worker_message operation.
//
// Display a Worker Message.
//
// GET /v2/workers/messages/{message_id}
func (UnimplementedHandler) GetSingleWorkerMessage(ctx context.Context, params GetSingleWorkerMessageParams) (r *ResponseModelMessage, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTeamSingle implements get_team_single operation.
//
// Details of a worker Team.
//
// GET /v2/teams/{team_id}
func (UnimplementedHandler) GetTeamSingle(ctx context.Context, params GetTeamSingleParams) (r GetTeamSingleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTeams implements get_teams operation.
//
// A List with the details of all teams.
//
// GET /v2/teams
func (UnimplementedHandler) GetTeams(ctx context.Context, params GetTeamsParams) (r []TeamDetails, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTextAsyncStatus implements get_text_async_status operation.
//
// This request will include all already generated texts.
//
// GET /v2/generate/text/status/{id}
func (UnimplementedHandler) GetTextAsyncStatus(ctx context.Context, params GetTextAsyncStatusParams) (r GetTextAsyncStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTextHordeStatsModels implements get_text_horde_stats_models operation.
//
// Details how many texts were generated per model for the past day, month and total.
//
// GET /v2/stats/text/models
func (UnimplementedHandler) GetTextHordeStatsModels(ctx context.Context, params GetTextHordeStatsModelsParams) (r *TxtModelStats, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTextHordeStatsTotals implements get_text_horde_stats_totals operation.
//
// Also shows the amount of pixelsteps for the same timeframe.
//
// GET /v2/stats/text/totals
func (UnimplementedHandler) GetTextHordeStatsTotals(ctx context.Context, params GetTextHordeStatsTotalsParams) (r *StatsTxtTotals, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTextStyle implements get_text_style operation.
//
// Can be filtered based on model or tags.
//
// GET /v2/styles/text
func (UnimplementedHandler) GetTextStyle(ctx context.Context, params GetTextStyleParams) (r []StyleKobold, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserSingle implements get_user_single operation.
//
// Details and statistics about a specific user.
//
// GET /v2/users/{user_id}
func (UnimplementedHandler) GetUserSingle(ctx context.Context, params GetUserSingleParams) (r GetUserSingleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUsers implements get_users operation.
//
// A List with the details and statistic of all registered users.
//
// GET /v2/users
func (UnimplementedHandler) GetUsers(ctx context.Context, params GetUsersParams) (r *UserDetails, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkerMessages implements get_worker_messages operation.
//
// List Worker Messages.
//
// GET /v2/workers/messages
func (UnimplementedHandler) GetWorkerMessages(ctx context.Context, params GetWorkerMessagesParams) (r GetWorkerMessagesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkerSingle implements get_worker_single operation.
//
// Can retrieve the details of a worker even if inactive
// (A worker is considered inactive if it has not checked in for 5 minutes).
//
// GET /v2/workers/{worker_id}
func (UnimplementedHandler) GetWorkerSingle(ctx context.Context, params GetWorkerSingleParams) (r GetWorkerSingleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkerSingleName implements get_worker_single_name operation.
//
// Can retrieve the details of a worker even if inactive
// (A worker is considered inactive if it has not checked in for 5 minutes).
//
// GET /v2/workers/name/{worker_name}
func (UnimplementedHandler) GetWorkerSingleName(ctx context.Context, params GetWorkerSingleNameParams) (r GetWorkerSingleNameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkers implements get_workers operation.
//
// A List with the details of all registered and active workers.
//
// GET /v2/workers
func (UnimplementedHandler) GetWorkers(ctx context.Context, params GetWorkersParams) (r []WorkerDetails, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchFilterSingle implements patch_filter_single operation.
//
// Moderator Only: Modify an existing regex filter.
//
// PATCH /v2/filters/{filter_id}
func (UnimplementedHandler) PatchFilterSingle(ctx context.Context, req *PatchExistingFilter, params PatchFilterSingleParams) (r PatchFilterSingleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchSharedKeySingle implements patch_shared_key_single operation.
//
// Modify an existing Shared Key.
//
// PATCH /v2/sharedkeys/{sharedkey_id}
func (UnimplementedHandler) PatchSharedKeySingle(ctx context.Context, req *SharedKeyInput, params PatchSharedKeySingleParams) (r PatchSharedKeySingleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchSingleCollection implements patch_single_collection operation.
//
// Modifies an existing style collection.
//
// PATCH /v2/collections/{collection_id}
func (UnimplementedHandler) PatchSingleCollection(ctx context.Context, req *InputModelCollection, params PatchSingleCollectionParams) (r PatchSingleCollectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchSingleImageStyle implements patch_single_image_style operation.
//
// Modifies an image style.
//
// PATCH /v2/styles/image/{style_id}
func (UnimplementedHandler) PatchSingleImageStyle(ctx context.Context, req *ModelStylePatchStable, params PatchSingleImageStyleParams) (r PatchSingleImageStyleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchSingleImageStyleExample implements patch_single_image_style_example operation.
//
// Modified an existing image style example.
//
// PATCH /v2/styles/image/{style_id}/example/{example_id}
func (UnimplementedHandler) PatchSingleImageStyleExample(ctx context.Context, req *InputStyleExamplePost, params PatchSingleImageStyleExampleParams) (r PatchSingleImageStyleExampleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchSingleTextStyle implements patch_single_text_style operation.
//
// Modifies a text style.
//
// PATCH /v2/styles/text/{style_id}
func (UnimplementedHandler) PatchSingleTextStyle(ctx context.Context, req *ModelStylePatchKobold, params PatchSingleTextStyleParams) (r PatchSingleTextStyleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchTeamSingle implements patch_team_single operation.
//
// Update a Team's information.
//
// PATCH /v2/teams/{team_id}
func (UnimplementedHandler) PatchTeamSingle(ctx context.Context, req *ModifyTeamInput, params PatchTeamSingleParams) (r PatchTeamSingleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostAesthetics implements post_aesthetics operation.
//
// AI
// The request has to have been sent as shared: true.
// You can select the best image in the set, and/or provide a rating for each or some images in the
// set.
// If you select best-of image, you will gain 4 kudos. Each rating is 5 kudos. Best-of will be
// ignored when ratings conflict with it.
// You can never gain more kudos than you spent for this generation. Your reward at max will be your
// kudos consumption - 1.
//
// POST /v2/generate/rate/{id}
func (UnimplementedHandler) PostAesthetics(ctx context.Context, req *AestheticsPayload, params PostAestheticsParams) (r PostAestheticsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostAwardKudos implements post_award_kudos operation.
//
// This API can only be used through privileged access.
//
// POST /v2/kudos/award
func (UnimplementedHandler) PostAwardKudos(ctx context.Context, req *PostAwardKudosReq, params PostAwardKudosParams) (r PostAwardKudosRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostCollection implements post_collection operation.
//
// Creates a new style collection.
//
// POST /v2/collections
func (UnimplementedHandler) PostCollection(ctx context.Context, req *InputModelCollection, params PostCollectionParams) (r PostCollectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostFilters implements post_filters operation.
//
// Moderator Only: Check The suspicion of the provided prompt.
//
// POST /v2/filters
func (UnimplementedHandler) PostFilters(ctx context.Context, req *PostFiltersReq, params PostFiltersParams) (r PostFiltersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostImageAsyncGenerate implements post_image_async_generate operation.
//
// This endpoint will immediately return with the UUID of the request for generation.
// This endpoint will always be accepted, even if there are no workers available currently to fulfill
// this request.
// Perhaps some will appear in the next 10 minutes.
// Asynchronous requests live for 10 minutes before being considered stale and being deleted.
//
// POST /v2/generate/async
func (UnimplementedHandler) PostImageAsyncGenerate(ctx context.Context, req *GenerationInputStable, params PostImageAsyncGenerateParams) (r PostImageAsyncGenerateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostImageJobPop implements post_image_job_pop operation.
//
// This endpoint is used by registered workers only.
//
// POST /v2/generate/pop
func (UnimplementedHandler) PostImageJobPop(ctx context.Context, req *PopInputStable, params PostImageJobPopParams) (r PostImageJobPopRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostImageJobSubmit implements post_image_job_submit operation.
//
// This endpoint is used by registered workers only.
//
// POST /v2/generate/submit
func (UnimplementedHandler) PostImageJobSubmit(ctx context.Context, req *SubmitInputStable, params PostImageJobSubmitParams) (r PostImageJobSubmitRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostImageStyle implements post_image_style operation.
//
// Creates a new image style.
//
// POST /v2/styles/image
func (UnimplementedHandler) PostImageStyle(ctx context.Context, req *ModelStyleInputStable, params PostImageStyleParams) (r PostImageStyleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostImageStyleExample implements post_image_style_example operation.
//
// Creates an image style example.
//
// POST /v2/styles/image/{style_id}/example
func (UnimplementedHandler) PostImageStyleExample(ctx context.Context, req *InputStyleExamplePost, params PostImageStyleExampleParams) (r PostImageStyleExampleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostInterrogate implements post_interrogate operation.
//
// This endpoint will immediately return with the UUID of the request for interrogation.
// This endpoint will always be accepted, even if there are no workers available currently to fulfill
// this request.
// Perhaps some will appear in the next 20 minutes.
// Asynchronous requests live for 20 minutes before being considered stale and being deleted.
//
// POST /v2/interrogate/async
func (UnimplementedHandler) PostInterrogate(ctx context.Context, req *ModelInterrogationInputStable, params PostInterrogateParams) (r PostInterrogateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostInterrogatePop implements post_interrogate_pop operation.
//
// This endpoint is used by registered workers only.
//
// POST /v2/interrogate/pop
func (UnimplementedHandler) PostInterrogatePop(ctx context.Context, req *InterrogationPopInput, params PostInterrogatePopParams) (r PostInterrogatePopRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostInterrogateSubmit implements post_interrogate_submit operation.
//
// This endpoint is used by registered workers only.
//
// POST /v2/interrogate/submit
func (UnimplementedHandler) PostInterrogateSubmit(ctx context.Context, req *PostInterrogateSubmitReq, params PostInterrogateSubmitParams) (r PostInterrogateSubmitRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostOperationsIP implements post_operations_ip operation.
//
// Only usable by horde moderators.
//
// POST /v2/operations/ipaddr
func (UnimplementedHandler) PostOperationsIP(ctx context.Context, req *AddTimeoutIPInput, params PostOperationsIPParams) (r PostOperationsIPRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostTeams implements post_teams operation.
//
// Only trusted users can create new teams.
//
// POST /v2/teams
func (UnimplementedHandler) PostTeams(ctx context.Context, req *CreateTeamInput, params PostTeamsParams) (r PostTeamsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostTextAsyncGenerate implements post_text_async_generate operation.
//
// This endpoint will immediately return with the UUID of the request for generation.
// This endpoint will always be accepted, even if there are no workers available currently to fulfill
// this request.
// Perhaps some will appear in the next 20 minutes.
// Asynchronous requests live for 20 minutes before being considered stale and being deleted.
//
// POST /v2/generate/text/async
func (UnimplementedHandler) PostTextAsyncGenerate(ctx context.Context, req *GenerationInputKobold, params PostTextAsyncGenerateParams) (r PostTextAsyncGenerateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostTextJobPop implements post_text_job_pop operation.
//
// This endpoint is used by registered workers only.
//
// POST /v2/generate/text/pop
func (UnimplementedHandler) PostTextJobPop(ctx context.Context, req *PopInputKobold, params PostTextJobPopParams) (r PostTextJobPopRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostTextJobSubmit implements post_text_job_submit operation.
//
// This endpoint is used by registered workers only.
//
// POST /v2/generate/text/submit
func (UnimplementedHandler) PostTextJobSubmit(ctx context.Context, req *SubmitInputKobold, params PostTextJobSubmitParams) (r PostTextJobSubmitRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostTextStyle implements post_text_style operation.
//
// Creates a new text style.
//
// POST /v2/styles/text
func (UnimplementedHandler) PostTextStyle(ctx context.Context, req *ModelStyleInputKobold, params PostTextStyleParams) (r PostTextStyleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostTransferKudos implements post_transfer_kudos operation.
//
// Transfer Kudos to another registed user.
//
// POST /v2/kudos/transfer
func (UnimplementedHandler) PostTransferKudos(ctx context.Context, req *PostTransferKudosReq, params PostTransferKudosParams) (r PostTransferKudosRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostWorkerMessages implements post_worker_messages operation.
//
// Create New Worker Message.
//
// POST /v2/workers/messages
func (UnimplementedHandler) PostWorkerMessages(ctx context.Context, req *ResponseModelMessage, params PostWorkerMessagesParams) (r PostWorkerMessagesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutFilters implements put_filters operation.
//
// Moderator Only: Add a new regex filter.
//
// PUT /v2/filters
func (UnimplementedHandler) PutFilters(ctx context.Context, req *PutNewFilter, params PutFiltersParams) (r PutFiltersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutHordeModes implements put_horde_modes operation.
//
// Endpoint for admins to (un)set the horde into maintenance, invite_only or raid modes.
//
// PUT /v2/status/modes
func (UnimplementedHandler) PutHordeModes(ctx context.Context, req *PutHordeModesReq, params PutHordeModesParams) (r PutHordeModesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutOperationsBlockWorkerIP implements put_operations_block_worker_ip operation.
//
// Only usable by horde moderators.
//
// PUT /v2/operations/block_worker_ipaddr/{worker_id}
func (UnimplementedHandler) PutOperationsBlockWorkerIP(ctx context.Context, req *AddWorkerTimeout, params PutOperationsBlockWorkerIPParams) (r PutOperationsBlockWorkerIPRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutSharedKey implements put_shared_key operation.
//
// Create a new SharedKey for this user.
//
// PUT /v2/sharedkeys
func (UnimplementedHandler) PutSharedKey(ctx context.Context, req *SharedKeyInput, params PutSharedKeyParams) (r PutSharedKeyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutUserSingle implements put_user_single operation.
//
// Endpoint for horde admins to perform operations on users.
//
// PUT /v2/users/{user_id}
func (UnimplementedHandler) PutUserSingle(ctx context.Context, req *ModifyUserInput, params PutUserSingleParams) (r PutUserSingleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutWorkerSingle implements put_worker_single operation.
//
// PUT /v2/workers/{worker_id}
func (UnimplementedHandler) PutWorkerSingle(ctx context.Context, req *ModifyWorkerInput, params PutWorkerSingleParams) (r PutWorkerSingleRes, _ error) {
	return r, ht.ErrNotImplemented
}
