// Code generated by ogen, DO NOT EDIT.

package aihorde

// setDefaults set default value of fields.
func (s *FilterDetails) setDefaults() {
	{
		val := string("")
		s.Replacement.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *FilterPromptSuspicion) setDefaults() {
	{
		val := string("0")
		s.Suspicion = val
	}
}

// setDefaults set default value of fields.
func (s *GenerationInputKobold) setDefaults() {
	{
		val := bool(false)
		s.TrustedWorkers.SetTo(val)
	}
	{
		val := bool(true)
		s.ValidatedBackends.SetTo(val)
	}
	{
		val := bool(true)
		s.SlowWorkers.SetTo(val)
	}
	{
		val := bool(false)
		s.WorkerBlacklist.SetTo(val)
	}
	{
		val := bool(false)
		s.DryRun.SetTo(val)
	}
	{
		val := bool(false)
		s.DisableBatching.SetTo(val)
	}
	{
		val := bool(false)
		s.AllowDowngrade.SetTo(val)
	}
	{
		val := bool(false)
		s.ExtraSlowWorkers.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GenerationInputStable) setDefaults() {
	{
		val := bool(false)
		s.Nsfw.SetTo(val)
	}
	{
		val := bool(false)
		s.TrustedWorkers.SetTo(val)
	}
	{
		val := bool(true)
		s.ValidatedBackends.SetTo(val)
	}
	{
		val := bool(true)
		s.SlowWorkers.SetTo(val)
	}
	{
		val := bool(false)
		s.ExtraSlowWorkers.SetTo(val)
	}
	{
		val := bool(false)
		s.CensorNsfw.SetTo(val)
	}
	{
		val := bool(false)
		s.WorkerBlacklist.SetTo(val)
	}
	{
		val := GenerationInputStableSourceProcessing("img2img")
		s.SourceProcessing.SetTo(val)
	}
	{
		val := bool(true)
		s.R2.SetTo(val)
	}
	{
		val := bool(false)
		s.Shared.SetTo(val)
	}
	{
		val := bool(true)
		s.ReplacementFilter.SetTo(val)
	}
	{
		val := bool(false)
		s.DryRun.SetTo(val)
	}
	{
		val := bool(false)
		s.DisableBatching.SetTo(val)
	}
	{
		val := bool(false)
		s.AllowDowngrade.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GenerationKobold) setDefaults() {
	{
		val := GenerationKoboldState("ok")
		s.State = val
	}
}

// setDefaults set default value of fields.
func (s *GenerationPayloadStable) setDefaults() {
	{
		val := GenerationPayloadStableSourceProcessing("img2img")
		s.SourceProcessing.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GenerationStable) setDefaults() {
	{
		val := GenerationStableState("ok")
		s.State = val
	}
}

// setDefaults set default value of fields.
func (s *InputModelCollection) setDefaults() {
	{
		val := bool(true)
		s.Public.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *InterrogationPopInput) setDefaults() {
	{
		val := string("unknown")
		s.BridgeAgent.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ModelGenerationInputStable) setDefaults() {
	{
		val := ModelGenerationInputStableSamplerName("k_euler_a")
		s.SamplerName.SetTo(val)
	}
	{
		val := bool(false)
		s.Karras.SetTo(val)
	}
	{
		val := bool(false)
		s.Tiling.SetTo(val)
	}
	{
		val := bool(false)
		s.HiresFix.SetTo(val)
	}
	{
		val := bool(false)
		s.Transparent.SetTo(val)
	}
	{
		val := bool(false)
		s.ImageIsControl.SetTo(val)
	}
	{
		val := bool(false)
		s.ReturnControlMap.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ModelInterrogationInputStable) setDefaults() {
	{
		val := bool(true)
		s.SlowWorkers.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ModelPayloadLorasStable) setDefaults() {
	{
		val := bool(false)
		s.IsVersion.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ModelPayloadStable) setDefaults() {
	{
		val := ModelPayloadStableSamplerName("k_euler_a")
		s.SamplerName.SetTo(val)
	}
	{
		val := bool(false)
		s.Karras.SetTo(val)
	}
	{
		val := bool(false)
		s.Tiling.SetTo(val)
	}
	{
		val := bool(false)
		s.HiresFix.SetTo(val)
	}
	{
		val := bool(false)
		s.Transparent.SetTo(val)
	}
	{
		val := bool(false)
		s.ImageIsControl.SetTo(val)
	}
	{
		val := bool(false)
		s.ReturnControlMap.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ModelStyleInputKobold) setDefaults() {
	{
		val := string("{p}")
		s.Prompt.SetTo(val)
	}
	{
		val := bool(true)
		s.Public.SetTo(val)
	}
	{
		val := bool(false)
		s.Nsfw.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ModelStyleInputStable) setDefaults() {
	{
		val := string("{p}{np}")
		s.Prompt.SetTo(val)
	}
	{
		val := bool(true)
		s.Public.SetTo(val)
	}
	{
		val := bool(false)
		s.Nsfw.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ModelStylePatchKobold) setDefaults() {
	{
		val := bool(true)
		s.Public.SetTo(val)
	}
	{
		val := bool(false)
		s.Nsfw.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ModelStylePatchStable) setDefaults() {
	{
		val := bool(true)
		s.Public.SetTo(val)
	}
	{
		val := bool(false)
		s.Nsfw.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ModifyUserInput) setDefaults() {
	{
		val := bool(false)
		s.GenerateProxyPasskey.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PatchExistingFilter) setDefaults() {
	{
		val := string("")
		s.Replacement.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PopInputKobold) setDefaults() {
	{
		val := bool(false)
		s.Nsfw.SetTo(val)
	}
	{
		val := string("unknown:0:unknown")
		s.BridgeAgent.SetTo(val)
	}
	{
		val := bool(false)
		s.RequireUpfrontKudos.SetTo(val)
	}
	{
		val := bool(true)
		s.ExtraSlowWorker.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PopInputStable) setDefaults() {
	{
		val := bool(false)
		s.Nsfw.SetTo(val)
	}
	{
		val := string("unknown:0:unknown")
		s.BridgeAgent.SetTo(val)
	}
	{
		val := bool(false)
		s.RequireUpfrontKudos.SetTo(val)
	}
	{
		val := bool(true)
		s.ExtraSlowWorker.SetTo(val)
	}
	{
		val := bool(true)
		s.AllowImg2img.SetTo(val)
	}
	{
		val := bool(true)
		s.AllowPainting.SetTo(val)
	}
	{
		val := bool(true)
		s.AllowUnsafeIpaddr.SetTo(val)
	}
	{
		val := bool(true)
		s.AllowPostProcessing.SetTo(val)
	}
	{
		val := bool(true)
		s.AllowControlnet.SetTo(val)
	}
	{
		val := bool(true)
		s.AllowSdxlControlnet.SetTo(val)
	}
	{
		val := bool(true)
		s.AllowLora.SetTo(val)
	}
	{
		val := bool(true)
		s.LimitMaxSteps.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PutNewFilter) setDefaults() {
	{
		val := string("")
		s.Replacement.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RequestStatusCheck) setDefaults() {
	{
		val := bool(false)
		s.Faulted.SetTo(val)
	}
	{
		val := bool(true)
		s.IsPossible.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RequestStatusKobold) setDefaults() {
	{
		val := bool(false)
		s.Faulted.SetTo(val)
	}
	{
		val := bool(true)
		s.IsPossible.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RequestStatusStable) setDefaults() {
	{
		val := bool(false)
		s.Faulted.SetTo(val)
	}
	{
		val := bool(true)
		s.IsPossible.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ResponseModelCollection) setDefaults() {
	{
		val := bool(true)
		s.Public.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SimpleResponse) setDefaults() {
	{
		val := string("OK")
		s.Message = val
	}
}

// setDefaults set default value of fields.
func (s *StyleKobold) setDefaults() {
	{
		val := string("{p}")
		s.Prompt.SetTo(val)
	}
	{
		val := bool(true)
		s.Public.SetTo(val)
	}
	{
		val := bool(false)
		s.Nsfw.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *StyleStable) setDefaults() {
	{
		val := string("{p}{np}")
		s.Prompt.SetTo(val)
	}
	{
		val := bool(true)
		s.Public.SetTo(val)
	}
	{
		val := bool(false)
		s.Nsfw.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SubmitInputKobold) setDefaults() {
	{
		val := SubmitInputKoboldState("ok")
		s.State.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SubmitInputStable) setDefaults() {
	{
		val := SubmitInputStableState("ok")
		s.State.SetTo(val)
	}
	{
		val := bool(false)
		s.Censored.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WorkerDetails) setDefaults() {
	{
		val := bool(false)
		s.Nsfw.SetTo(val)
	}
	{
		val := string("unknown:0:unknown")
		s.BridgeAgent = val
	}
}
