// Code generated by ogen, DO NOT EDIT.
package aihorde

type DeleteFilterSingleRes interface {
	deleteFilterSingleRes()
}

type DeleteImageAsyncStatusRes interface {
	deleteImageAsyncStatusRes()
}

type DeleteInterrogationStatusRes interface {
	deleteInterrogationStatusRes()
}

type DeleteOperationsBlockWorkerIPRes interface {
	deleteOperationsBlockWorkerIPRes()
}

type DeleteOperationsIPRes interface {
	deleteOperationsIPRes()
}

type DeleteSharedKeySingleRes interface {
	deleteSharedKeySingleRes()
}

type DeleteSingleCollectionRes interface {
	deleteSingleCollectionRes()
}

type DeleteSingleImageStyleExampleRes interface {
	deleteSingleImageStyleExampleRes()
}

type DeleteSingleImageStyleRes interface {
	deleteSingleImageStyleRes()
}

type DeleteSingleTextStyleRes interface {
	deleteSingleTextStyleRes()
}

type DeleteTeamSingleRes interface {
	deleteTeamSingleRes()
}

type DeleteTextAsyncStatusRes interface {
	deleteTextAsyncStatusRes()
}

type DeleteUserSingleRes interface {
	deleteUserSingleRes()
}

type DeleteWorkerSingleRes interface {
	deleteWorkerSingleRes()
}

type GetDocsPrivacyRes interface {
	getDocsPrivacyRes()
}

type GetDocsSponsorsRes interface {
	getDocsSponsorsRes()
}

type GetDocsTermsRes interface {
	getDocsTermsRes()
}

type GetFilterRegexRes interface {
	getFilterRegexRes()
}

type GetFilterSingleRes interface {
	getFilterSingleRes()
}

type GetFiltersRes interface {
	getFiltersRes()
}

type GetFindUserRes interface {
	getFindUserRes()
}

type GetImageAsyncCheckRes interface {
	getImageAsyncCheckRes()
}

type GetImageAsyncStatusRes interface {
	getImageAsyncStatusRes()
}

type GetImageHordeStatsModelsRes interface {
	getImageHordeStatsModelsRes()
}

type GetInterrogationStatusRes interface {
	getInterrogationStatusRes()
}

type GetModelsRes interface {
	getModelsRes()
}

type GetOperationsIPRes interface {
	getOperationsIPRes()
}

type GetOperationsIPSingleRes interface {
	getOperationsIPSingleRes()
}

type GetSharedKeySingleRes interface {
	getSharedKeySingleRes()
}

type GetTeamSingleRes interface {
	getTeamSingleRes()
}

type GetTextAsyncStatusRes interface {
	getTextAsyncStatusRes()
}

type GetUserSingleRes interface {
	getUserSingleRes()
}

type GetWorkerMessagesRes interface {
	getWorkerMessagesRes()
}

type GetWorkerSingleNameRes interface {
	getWorkerSingleNameRes()
}

type GetWorkerSingleRes interface {
	getWorkerSingleRes()
}

type PatchFilterSingleRes interface {
	patchFilterSingleRes()
}

type PatchSharedKeySingleRes interface {
	patchSharedKeySingleRes()
}

type PatchSingleCollectionRes interface {
	patchSingleCollectionRes()
}

type PatchSingleImageStyleExampleRes interface {
	patchSingleImageStyleExampleRes()
}

type PatchSingleImageStyleRes interface {
	patchSingleImageStyleRes()
}

type PatchSingleTextStyleRes interface {
	patchSingleTextStyleRes()
}

type PatchTeamSingleRes interface {
	patchTeamSingleRes()
}

type PostAestheticsRes interface {
	postAestheticsRes()
}

type PostAwardKudosRes interface {
	postAwardKudosRes()
}

type PostCollectionRes interface {
	postCollectionRes()
}

type PostFiltersRes interface {
	postFiltersRes()
}

type PostImageAsyncGenerateRes interface {
	postImageAsyncGenerateRes()
}

type PostImageJobPopRes interface {
	postImageJobPopRes()
}

type PostImageJobSubmitRes interface {
	postImageJobSubmitRes()
}

type PostImageStyleExampleRes interface {
	postImageStyleExampleRes()
}

type PostImageStyleRes interface {
	postImageStyleRes()
}

type PostInterrogatePopRes interface {
	postInterrogatePopRes()
}

type PostInterrogateRes interface {
	postInterrogateRes()
}

type PostInterrogateSubmitRes interface {
	postInterrogateSubmitRes()
}

type PostOperationsIPRes interface {
	postOperationsIPRes()
}

type PostTeamsRes interface {
	postTeamsRes()
}

type PostTextAsyncGenerateRes interface {
	postTextAsyncGenerateRes()
}

type PostTextJobPopRes interface {
	postTextJobPopRes()
}

type PostTextJobSubmitRes interface {
	postTextJobSubmitRes()
}

type PostTextStyleRes interface {
	postTextStyleRes()
}

type PostTransferKudosRes interface {
	postTransferKudosRes()
}

type PostWorkerMessagesRes interface {
	postWorkerMessagesRes()
}

type PutFiltersRes interface {
	putFiltersRes()
}

type PutHordeModesRes interface {
	putHordeModesRes()
}

type PutOperationsBlockWorkerIPRes interface {
	putOperationsBlockWorkerIPRes()
}

type PutSharedKeyRes interface {
	putSharedKeyRes()
}

type PutUserSingleRes interface {
	putUserSingleRes()
}

type PutWorkerSingleRes interface {
	putWorkerSingleRes()
}
